
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu May 09 20:31:50 EDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 33;
  public static final int CHAR = 27;
  public static final int GE = 20;
  public static final int CHAR_LITERAL = 34;
  public static final int LPAREN = 2;
  public static final int SEMI = 6;
  public static final int INT = 28;
  public static final int STAR = 10;
  public static final int RPAREN = 3;
  public static final int NOT = 12;
  public static final int AND = 13;
  public static final int LT = 17;
  public static final int OR = 14;
  public static final int COMMA = 7;
  public static final int DIV = 11;
  public static final int ASSIGN = 21;
  public static final int IF = 22;
  public static final int LE = 18;
  public static final int EOF = 0;
  public static final int BOOLEAN = 30;
  public static final int RETURN = 25;
  public static final int TRUE = 36;
  public static final int error = 1;
  public static final int ADD = 8;
  public static final int VOID = 31;
  public static final int EQ = 15;
  public static final int ERROR = 38;
  public static final int LBRACE = 4;
  public static final int ELSE = 23;
  public static final int WHILE = 24;
  public static final int RBRACE = 5;
  public static final int NE = 16;
  public static final int STRING = 29;
  public static final int FALSE = 37;
  public static final int GT = 19;
  public static final int SUB = 9;
  public static final int PRINT = 26;
  public static final int INT_LITERAL = 35;
  public static final int IDENTIFIER = 32;
}

